version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - wallet-api-service
    environment:
      - REACT_APP_API_URL=http://localhost:5001

  wallet-api-service:
    build: ./wallet-api-service
    ports:
      - "5001:5001"
    volumes:
      - ./wallet-api-service:/app
      - /app/node_modules
    environment:
      - PORT=5001
      - DB_SERVICE_URL=http://wallet-db-service:5002
    depends_on:
      - wallet-db-service

  wallet-db-service:
    build: ./wallet-db-service
    ports:
      - "5002:5002"
    volumes:
      - ./wallet-db-service:/app
      - /app/node_modules
    environment:
      - PORT=5002
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=wallet_db
      - DB_PORT=5432
      - EMAIL_FEATURE=false
      - EMAIL_USER=your-email@gmail.com
      - EMAIL_PASSWORD=your-password
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wallet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
    command: >
      postgres
      -c shared_buffers=256MB
      -c max_connections=50

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './postgres-data' 